steps:
# Generate provider.tf from script
- name: 'bash'
  args:
    - '-c'
    - |
      echo "terraform { 
        required_providers { 
          google      = { 
            source  = \"hashicorp/google\" 
            version = \"${_GOOGLE_PROVIDER_VERSION}\" 
      } 
      google-beta = { 
      source  = \"hashicorp/google-beta\" 
      version = \"${_GOOGLE_BETA_PROVIDER_VERSION}\" }
      }
      }" > provider.tf
# Build docker image
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '--tag=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_BUILDER_IMAGE_NAME}',
    '--build-arg=TERRAFORM_VERSION=${_TERRAFORM_VERSION}',
    '--build-arg=TERRAFORM_VERSION_SHA256SUM=${_TERRAFORM_VERSION_SHA256SUM}',
    '--build-arg=TERRAFORM_VALIDATOR_RELEASE=${_TERRAFORM_VALIDATOR_RELEASE}',
    '--build-arg=HELM_VERSION=${_HELM_VERSION}',
    '--build-arg=HELM_SHA256=${_HELM_SHA256}',
    '--build-arg=HELMFILE_VERSION=${_HELMFILE_VERSION}',
    '--build-arg=KUBECTL_VERSION=${_KUBECTL_VERSION}',
    '.'
    ]
# Run 'version' in built image
- name: '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_BUILDER_IMAGE_NAME}'
  args: ['version']
substitutions:
  _TERRAFORM_VERSION: '1.0.11' # default value
  _TERRAFORM_VERSION_SHA256SUM: 'eeb46091a42dc303c3a3c300640c7774ab25cbee5083dafa5fd83b54c8aca664' # default value
  _TERRAFORM_VALIDATOR_RELEASE: 'v0.4.0' # default value
  _HELM_VERSION: 'v3.7.0' # default value
  _HELM_SHA256: '096e30f54c3ccdabe30a8093f8e128dba76bb67af697b85db6ed0453a2701bf9' # default value
  _HELMFILE_VERSION: 'v0.142.0' # default value
  _KUBECTL_VERSION: 'v1.22.4' # default value
  _GOOGLE_PROVIDER_VERSION: '4.1' # default value
  _GOOGLE_BETA_PROVIDER_VERSION: '4.1' # default value
images: ['${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_BUILDER_IMAGE_NAME}']
